### ISSUE TITLE
Issues with watch-stack when using awspowershell.netcore

### ISSUE THREAD

**Issue by adrian-andersson** [scrthq/VaporShell#57]
Example is Watch-Stack

```
PS: > watch-stack 'example-stack'                                                                     
STACK NAME(S) : example-stack
REFRESH       : 2 seconds

watch-stack : Method invocation failed because [Amazon.CloudFormation.AmazonCloudFormationClient] does not contain a
method named 'DescribeStackEvents'.
At line:1 char:1
+ watch-stack 'example-stack'
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Watch-Stack], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound,Watch-Stack
```

I checked. [Amazon.CloudFormation.AmazonCloudFormationClient] in awspowershell.netcore does not contain this method (DescribeStackEvents), the error is correct.

Can we use DescribeStackEventsAsync when netcore Aws is used?

**Comment by scrthq** [comment]
Hey @adrian-andersson - Should have this fixed and rolled out shortly! All of the method expansion for the Core methods is done on the private function `ProcessRequest4`, which currently runs the Async method if `$IsCoreCLR` is `$true`. Since the AWSPowerShell.NetCore module and the newer AWS.Tools.* modules all use the same netstandard library, I'm switching that condition to check if the Async method is present and using it if so rather than checking if PowerShell Core is in use.

Testing now, but quick fix none the less! I'll let you know here once deployed 😄

**Comment by scrthq** [comment]
v2.8.0 available now @adrian-andersson. Let me know if you have any issues!
